### ISSUE TITLE
CONSUMER_INSTANCE_OPTS ?

### ISSUE THREAD

**Issue by askhogan** [evansolomon/nodejs-kinesis-client-library#10]
Nothing in the docs speak to what this is CONSUMER_INSTANCE_OPTS

I looked at the AWS env options and it doesnt include these

undefined:1
undefined
^
SyntaxError: Unexpected token u
    at Object.parse (native)
    at Function.AbstractConsumer.extend

**Comment by askhogan** [comment]
var opts = JSON.parse(process.env.CONSUMER_INSTANCE_OPTS);

**Comment by evansolomon** [comment]
It's just an internal thing used to pass data between processes via environment variables.

Can you show me what your setup looks like that leads to this error?  It sounds like maybe you are running the consumer directly rather than letting the cluster spawn it.  You can see where that data is set [here](https://github.com/evansolomon/nodejs-kinesis-client-library/blob/56657f7006a47f08d1aadcad9f0fc3055d33539c/src/ConsumerCluster.ts#L266-L283).

**Comment by evansolomon** [comment]
It's just an internal thing used to pass data between processes via environment variables.

Can you show me what your setup looks like that leads to this error?  It sounds like maybe you are running the consumer directly rather than letting the cluster spawn it.  You can see where that data is set [here](https://github.com/evansolomon/nodejs-kinesis-client-library/blob/56657f7006a47f08d1aadcad9f0fc3055d33539c/src/ConsumerCluster.ts#L266-L283).

**Comment by evansolomon** [comment]
It's just an internal thing used to pass data between processes via environment variables.

Can you show me what your setup looks like that leads to this error?  It sounds like maybe you are running the consumer directly rather than letting the cluster spawn it.  You can see where that data is set [here](https://github.com/evansolomon/nodejs-kinesis-client-library/blob/56657f7006a47f08d1aadcad9f0fc3055d33539c/src/ConsumerCluster.ts#L266-L283).
