### ISSUE TITLE
Scaling consumer on same kinesis stream

### ISSUE THREAD

**Issue by sfai05** [evansolomon/nodejs-kinesis-client-library#21]
Its it possible to scale more consumer to process data in the same stream ? My kinesis stream have large data inflow and the consumer have not enough power to process the data

**Comment by evansolomon** [comment]
The library supports one consumer process per shard. If the consumer can't keep up with the data in the stream, then the default solution would be to split the stream into more shards.

**Comment by sfai05** [comment]
I have split my stream into 2 stream and the old shard `shardId-000000000000` is closed but the consumer is still trying to access it. Got lots of error like this : 

```
{"name":"KinesisConsumer","streamName":"stream_name","shardId":"shardId-000000000000","hostname":"ip","pid":14654,"level":50,"err":{"message":"Shard shardId-000000000000 in stream stream_name under account does not exist","name":"ResourceNotFoundException","stack":"ResourceNotFoundException: Shard shardId-000000000000 in stream stream_name under account does not exist\n    at Request.extractError (/consumer-nodejs/node_modules/aws-sdk/lib/protocol/json.js:43:27)\n    at Request.callListeners (/consumer-nodejs/node_modules/aws-sdk/lib/sequential_executor.js:105:20)\n    at Request.emit (/consumer-nodejs/node_modules/aws-sdk/lib/sequential_executor.js:77:10)\n    at Request.emit (/consumer-nodejs/node_modules/aws-sdk/lib/request.js:595:14)\n    at Request.transition (/consumer-nodejs/node_modules/aws-sdk/lib/request.js:21:10)\n    at AcceptorStateMachine.runTo (/consumer-nodejs/node_modules/aws-sdk/lib/state_machine.js:14:12)\n    at /consumer-nodejs/node_modules/aws-sdk/lib/state_machine.js:26:10\n    at Request.<anonymous> (/consumer-nodejs/node_modules/aws-sdk/lib/request.js:37:9)\n    at Request.<anonymous> (/consumer-nodejs/node_modules/aws-sdk/lib/request.js:597:12)\n    at Request.callListeners (/consumer-nodejs/node_modules/aws-sdk/lib/sequential_executor.js:115:18)","code":"ResourceNotFoundException"},"msg":"Shard shardId-000000000000 in stream stream_name under account 351233380906 does not exist","time":"2015-10-08T03:22:36.199Z","v":0}
```

**Comment by sfai05** [comment]
And I found that another problem that slow down the process is I got lots of `The conditional request failed`

**Comment by sfai05** [comment]
I solved the reading old shard problem by deleting the table in DynamoDB

**Comment by evansolomon** [comment]
It's odd for the shard to not exist anymore once the stream is split. Did you do anything else? How long after you split the stream did you see that message?

> I got lots of The conditional request failed

The logging for this can be quite ugly, but those errors on their own are not necessarily a problem. The library uses Dynamo's consistent read feature as the source of truth to avoid race conditions, and that message usually just mean that multiple processors tried to do the same thing at the same time.

**Comment by sfai05** [comment]
@evansolomon When I split the stream into two AWS is actually create two new shard `shardId-000000000001` and `shardId-000000000002` and the old shard `shardId-000000000000` is closed for new events but its still accessible coz theres still some events inside. The old shard `shardId-000000000000` will auto closed when no events in the shard.

**Comment by sfai05** [comment]
@evansolomon I checked my data and theres no missing data even the `ConditionalCheckFailedException` occur. But when `ConditionalCheckFailedException` occur the consumer will perform the shutdown process and re-spawn which slow down the process

**Comment by sfai05** [comment]
@evansolomon what makes the process tried to access the same shard ? I have checked my `processRecords` function, it usually take 2 to 3 seconds to finish the process

**Comment by evansolomon** [comment]
> But when ConditionalCheckFailedException occur the consumer will perform the shutdown process and re-spawn which slow down the process

Yea, this is true. Currently the library takes a very naive approach here in favor of simplicity at the expense of performance. I'm open to other approaches but haven't gone farther on this myself because in my own usage this has never been an issue.

> what makes the process tried to access the same shard ? I have checked my processRecords function, it usually take 2 to 3 seconds to finish the process

The cluster checks what shards exist on the stream and compares them to what shards are currently "leased" by processors (stored in DynamoDB). Relevant code is in [ConsumerCluster._fetchAvailableShard](https://github.com/evansolomon/nodejs-kinesis-client-library/blob/7cfd9db2eee14e7b47601048df49eeb0508a0324/src/ConsumerCluster.ts#L252).

**Comment by sfai05** [comment]
@evansolomon Can I understand as : 
We spawn some consumer to help us process data and each shard only able to serve one consumer in the same time. When the process is done `done(null, true)` the consumer will try to find another shard thats not leased by a consumer. However race condition may take place here so we use DynamoDB to prevent this ?

**Comment by evansolomon** [comment]
Not quite. I'll try to explain the flow a bit better.

There is a thing called a cluster (this is roughly what gets created when the CLI command is run). It continuously looks for shards that are not being consumed. When it finds one it spawns a consumer to track the shard and gives it a "lease counter". The lease counter is a number stored in Dynamo that monotonically increases.

The lease counter and an expiration time are updated every 5 seconds and each update is predicated on the counter in Dynamo being what we last set it to. This is the part that prevents race conditions, since if multiple consumers try to update the same counter only one will work. The ConditionalCheckFailedException errors usually come from multiple consumers being spawned for the same lease (which often happens when the spawn process is slow for whatever reason).

As long as the consumer is alive and able to renew its lease, it will track the shard. If any of those things stop happening the consumer will exit, its lease will eventually expire, and the cluster (or another cluster, if they exist) will spawn a new consumer to process it.

Passing true to the callback's second argument doesn't affect what shard is being processed, it just tells the consumer process to mark a checkpoint in Dynamo so that if/when a new consumer is spawned for that shard it knows what record to being processing from. For many use cases it makes sense to always pass true there, but for others, like buffering data, you only want to do it once in a while.

Let me know if that clarifies what's going on.

**Comment by sfai05** [comment]
@evansolomon thats a very detailed and clear explanation. Thanks a lot !
