### ISSUE TITLE
How to limit the number of active consumers(child Process)

### ISSUE THREAD

**Issue by knexp** [evansolomon/nodejs-kinesis-client-library#22]
Hi,

I'm frequently getting this error 

Error 1: "stack":"ConditionalCheckFailedException: The conditional request failed\

Error 2 : Frequently getting memory leak , nearly 12 consumer processor is created,even though no data in kinesis.

do you have any idea why I'm getting error 1 and error 2?

Thanks In Advance

**Comment by evansolomon** [comment]
These two things are probably related. Here's what happens (check out the ["terminology" section of the readme](https://github.com/evansolomon/nodejs-kinesis-client-library#terminology) if any of this is confusing.

Every five seconds, the cluster checks the network to see if there are any shards that have not been locked by consumers (relevant code [here](https://github.com/evansolomon/nodejs-kinesis-client-library/blob/7cfd9db2eee14e7b47601048df49eeb0508a0324/src/ConsumerCluster.ts#L418-L435). If there are, then it spawns a consumer to process that shard. Five seconds later it will run the same check...forever.

The important thing to note here is that the cluster does not keep track of what shards its consumers are supposed to be working on. It is entirely the consumer's job to report that data to DynamoDB, which is in turn what the cluster checks.

Here is usually what causes a bunch of `ConditionalCheckFailedException` errors:

* Cluster checks for available shards, finds one, and spawns a consumer
* Consumer process starts up, which includes the actual node process starting, its initialize method running, etc
* More than 5 seconds goes by and the consumer process has not reserved its lease in Dynamo yet
* The cluster runs the check again, finds and available shard — this is the same one it found before and spawned a consumer for, but it doesn't care — and spawns a consumer

Let's say that for whatever reason it takes the consumer 30 seconds to try to reserve its lease. In that time a bunch of other consumers will have been started. Only one of those consumers is going to successfully lock that shard; all the others will fail with a `ConditionalCheckFailedException` error. This is actually a good thing, it's how race conditions are prevented even across consumers that are on different machines.

So the `ConditionalCheckFailedException` error is generally okay to ignore. It probably shouldn't really even be logged as an "error". But I totally agree that seeing a ton of logs about it is annoying.

Off the top of my head, there are a couple ways that this could be made better:

1. Change the way the error `ConditionalCheckFailedException` error is logged, e.g. use `logger.debug()` instead of `logger.error()`
2. Change the five second loop to something longer and/or customizable (e.g. with a command line argument)
3. Make the cluster process a little smarter about not spawning consumers for shards that already have consumers running for them

It's worth noting that 3 is somewhat risky because it introduces a possibility that a consumer will not be spawned when one *should* be. Right now the library errs on the side of spawning a consumer more often than it should and letting DynamoDB's conditional writes be the arbiter of which one wins.

Every time I've seen this sort of thing happen, the processes will eventually stabilize after some consumer does succeed at locking its shard and the other ones exit. So those of 12 consumer processes I'd expect 1 to eventually lock its shard and the other 11 (plus more than may be launched in the meantime) to get this conditional check error, fail, and exit.

Finally, I get why you call it a memory leak but it's just worth noting that it's not really a memory leak in the traditional sense. It's not a case of memory failing to be freed up when it should be, it's more of a case of the program choosing to use more memory (via using more processes) in exchange for a little more simplicity. I realize there very well may be scenarios where that turns out to be a bad tradeoff.

Sorry this was such a long answer, but hopefully something in here helps.

**Comment by knexp** [comment]
Thansks Evansolomon for the detailed explaination. :+1: 
 I'm going through it, :)

**Comment by knexp** [comment]
Hi EvanSolomon,
""More than 5 seconds goes by and the consumer process has not reserved its lease in Dynamo yet
The cluster runs the check again, finds and available shard — this is the same one it found before and spawned a consumer for, but it doesn't care — and spawns a consumer""


So within 5 sec, the consumer should complete the processing for the retrieved data and should lease it, or else it'll spawn new consumer from the latest checkpoint.

Am I understood right ?

**Comment by evansolomon** [comment]
No not quite. It doesn't really matter how long it takes to process the data as long as you don't block the thread. In other words, a long setTimeout would be fine. A long while loop would not be fine. The 5 seconds are meaningful in terms of how long it takes the consumer to be ready. So that includes loading whatever code it needs and running its initialize method, if one exists. Sometimes this is very fast, sometimes it can be very slow, e.g. very large imports, slow machine, etc.

Also, just in case it's unclear, the consumer doesn't need to (and shouldn't try to) do anything to explicitly reserve a lease. That is all done automatically.

**Comment by knexp** [comment]
Thanks for explaination.

**Comment by knexp** [comment]
I have managed to limi the consumer to fetch less records --num-records to 1000, hope will not see those errors. Thanks Evansolomon. you can close this issue.
