### ISSUE TITLE
isFinished is set to 1 and kcl becomes idle.

### ISSUE THREAD

**Issue by knexp** [evansolomon/nodejs-kinesis-client-library#25]
Hi @evansolomon,

In DynamoDb table , there is column isFinished which is set to 1 and the processing from kinesis is not done(active consumer is 0), why is this happening and how to resume it ?

Thanks in Advance

**Comment by evansolomon** [comment]
I have seen this happen before. I believe it is caused by the Kinesis API incorrectly returning `null` for the `NextShardIterator` property [here](https://github.com/evansolomon/nodejs-kinesis-client-library/blob/7cfd9db2eee14e7b47601048df49eeb0508a0324/src/AbstractConsumer.ts#L249-L253).

The simplest fix is to delete the isFinished property in Dynamo. Obviously that is not a great solution, unfortunately.

**Comment by knexp** [comment]
Thanks @evansolomon  for the reply. Any workaround that this will not occur again..?

**Comment by evansolomon** [comment]
Not that I know of, unfortunately. I *think* the cause is bad data coming from Amazon.

**Comment by knexp** [comment]
just for information, how frequent you have faced this problem?

**Comment by evansolomon** [comment]
I saw it 2 or 3 times, I think, in the span of a couple months. Since then I have not seen it in around a year, I think. So pretty infrequent.

**Comment by knexp** [comment]
thanks @evansolomon for the information .
